# Generated by Django 3.2.5 on 2022-03-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_id', models.IntegerField(verbose_name='公寓编号')),
                ('flat_name', models.CharField(max_length=20, verbose_name='公寓名称')),
                ('flat_number', models.IntegerField(verbose_name='所住人数')),
                ('flat_teacher', models.CharField(max_length=20, verbose_name='管理老师')),
                ('flat_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(verbose_name='学号')),
                ('student_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('student_gender', models.CharField(max_length=5, verbose_name='性别')),
                ('student_math', models.IntegerField(verbose_name='数学成绩')),
                ('student_chinese', models.IntegerField(verbose_name='语文成绩')),
                ('student_english', models.IntegerField(verbose_name='英语成绩')),
                ('student_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flats', verbose_name='所住公寓')),
            ],
        ),
    ]
