# Generated by Django 3.2.5 on 2022-03-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='flat_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
