# Generated by Django 3.2.5 on 2022-03-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usernmae',
            new_name='username',
        ),
    ]
