# Generated by Django 3.2.5 on 2022-03-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_usernmae_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passworld',
            new_name='password',
        ),
    ]
